#!/bin/bash

#实现无密码远程一群主机
#使用前提：将所有要远程的ip，定义为变量IPS
#$PASSWORD为所有要远程的主机的一样的密码

###################################################
#for ip in $IPS
#do
#ssh_copy_id  $ip  $PASSWORF
#done
###################################################
ssh_copy_id (){
	rpm -q expect || yum -y install expect  
	[ -e /root/.ssh/id_rsa ] || ssh-keygen   -f /root/.ssh/id_rsa    -N '' 

         expect -c "set timeout -1;
         spawn ssh-copy-id $1;                                
         expect {
                 *(yes/no)*  {send -- yes\r;exp_continue;}
                 *password:* {send -- $2\r;exp_continue;}  
                 eof         {exit 0;}
         }";
 
}   &>   /dev/null
